language: go
go: 1.5
install:
    - go get -v code.google.com/p/go.tools/cmd/cover
script:
    - go test -v ./... -covermode=count -coverprofile=profile.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=profile.cov -service=travis-ci
notifications:
  email: false
